In [1]:
import polars as pl

In [2]:
dmo = pl.read_csv(
    "/home/spn1560/coarse-grain-rxns/data/processed/rules/mechinferred_dt_059_rules_before_2015_direct_mcsa_only_w_coreactants.tsv",
    separator="\t",
)
dmo.head()

shape: (5, 4)
┌────────┬───────────┬─────────────────────────────────┬───────────┐
│ Name   ┆ Reactants ┆ SMARTS                          ┆ Products  │
│ ---    ┆ ---       ┆ ---                             ┆ ---       │
│ str    ┆ str       ┆ str                             ┆ str       │
╞════════╪═══════════╪═════════════════════════════════╪═══════════╡
│ 6245_0 ┆ Any;WATER ┆ [C&D2&v4&H1&+0&!R&z0:1]=[C&D2&… ┆ Any;Any   │
│ 1989_0 ┆ Any;WATER ┆ [C&D1&v4&H2&+0&!R&z0:1]=[C&D2&… ┆ Any;Any   │
│ 2992_0 ┆ CoA;Any   ┆ [*:1](~[*:2]~[*:3]~[*:4](~[O&D… ┆ Any;Any   │
│ 6361_0 ┆ Any;Any   ┆ [*:1](~[O&D1&v2&H1&+0&!R:2])(~… ┆ CoA;Any   │
│ 598_0  ┆ Any       ┆ [O&D2&v2&H0&+0&R:1]-[C&D3&v4&H… ┆ WATER;Any │
└────────┴───────────┴─────────────────────────────────┴───────────┘

In [3]:
b15 = pl.read_csv(
    "/home/spn1560/coarse-grain-rxns/data/processed/rules/mechinferred_dt_009_rules_before_2015_w_coreactants.tsv",
    separator="\t",
)
b15.head()

shape: (5, 4)
┌────────┬───────────┬─────────────────────────────────┬───────────┐
│ Name   ┆ Reactants ┆ SMARTS                          ┆ Products  │
│ ---    ┆ ---       ┆ ---                             ┆ ---       │
│ str    ┆ str       ┆ str                             ┆ str       │
╞════════╪═══════════╪═════════════════════════════════╪═══════════╡
│ 304_0  ┆ Any;WATER ┆ [N&D2&v3&H1&+0&!R:1]-[C&D2&v4&… ┆ Any;Any   │
│ 1847_0 ┆ Any;WATER ┆ [C&D1&v4&H2&+0&!R&z0:1]=[C&D2&… ┆ Any;Any   │
│ 2826_0 ┆ CoA;Any   ┆ [*:1](~[*:2]~[*:3]~[*:4](~[O&D… ┆ Any;Any   │
│ 5145_0 ┆ Any;Any   ┆ [C&D3&v4&H0&+0&!R&z2:1](=[O&D1… ┆ CoA;Any   │
│ 559_0  ┆ Any       ┆ [O&D2&v2&H0&+0&R:1]~[*:2](~[*:… ┆ WATER;Any │
└────────┴───────────┴─────────────────────────────────┴───────────┘

In [4]:
dmo.with_columns(
    pl.col("SMARTS").str.len_chars().alias("SMARTS_length")
).select(
    pl.col("SMARTS_length").mean()
)

shape: (1, 1)
┌───────────────┐
│ SMARTS_length │
│ ---           │
│ f64           │
╞═══════════════╡
│ 1343.493134   │
└───────────────┘

In [5]:
b15.with_columns(
    pl.col("SMARTS").str.len_chars().alias("SMARTS_length")
).select(
    pl.col("SMARTS_length").mean()
)

shape: (1, 1)
┌───────────────┐
│ SMARTS_length │
│ ---           │
│ f64           │
╞═══════════════╡
│ 1223.925061   │
└───────────────┘

In [6]:
dmo.with_columns(
    pl.col("SMARTS").str.len_chars().alias("SMARTS_length")
).select(
    pl.col("SMARTS_length").max()
)

shape: (1, 1)
┌───────────────┐
│ SMARTS_length │
│ ---           │
│ u32           │
╞═══════════════╡
│ 5214          │
└───────────────┘

In [7]:
b15.with_columns(
    pl.col("SMARTS").str.len_chars().alias("SMARTS_length")
).select(
    pl.col("SMARTS_length").max()
)

shape: (1, 1)
┌───────────────┐
│ SMARTS_length │
│ ---           │
│ u32           │
╞═══════════════╡
│ 5130          │
└───────────────┘

In [8]:
st = pl.read_csv(
    "/home/spn1560/coarse-grain-rxns/artifacts/starters/after_2015_cpds.csv",
    separator=","
)
st.head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ id                              ┆ smiles                          │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ propanal                        ┆ CCC=O                           │
│ sphing-4-enine 1-phosphate      ┆ CCCCCCCCCCCCCC=CC(O)C(N)COP(=O… │
│ indole-3-carbaldehyde           ┆ O=Cc1c[nH]c2ccccc12             │
│ enol-oxaloacetate               ┆ O=C(O)C=C(O)C(=O)O              │
│ 2,4,7,9-tetrahydroxy-6-methyl-… ┆ C=CC(C)(C)c1c(O)c2c3c(c(O)cc(C… │
└─────────────────────────────────┴─────────────────────────────────┘

In [12]:
dss = [50, 100, 25]
for ds in dss:
    ds_st = st[::ds]
    print(f"Dataset: {ds}, Number of compounds: {len(ds_st)}")

    ds_st.write_csv(f"/home/spn1560/coarse-grain-rxns/artifacts/starters/after_2015_cpds_ds_{ds}.csv", separator=",")

Dataset: 50, Number of compounds: 44
Dataset: 100, Number of compounds: 22
Dataset: 25, Number of compounds: 88